# Generated by Django 4.1.7 on 2023-03-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.TextField()),
                ("doctor_hospital_name", models.TextField()),
                ("doctor_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PatientInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.TextField()),
                ("patient_dob", models.DateTimeField(verbose_name="Date of Birth")),
                ("patient_height", models.BigIntegerField()),
                ("patient_weight", models.BigIntegerField()),
                ("patient_history", models.TextField()),
                ("patient_allergies", models.TextField()),
                ("patient_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.BigIntegerField()),
                ("doctor_id", models.BigIntegerField()),
                ("prescription_desc", models.TextField()),
                ("hash_id", models.CharField(max_length=255)),
            ],
        ),
    ]
