# Generated by Django 4.1.7 on 2023-03-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorinformation",
            old_name="doctor_hospital_name",
            new_name="hospital_name",
        ),
        migrations.RenameField(
            model_name="doctorinformation",
            old_name="doctor_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="patient_allergies",
            new_name="allergies",
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="patient_dob",
            new_name="dob",
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="patient_height",
            new_name="height",
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="patient_history",
            new_name="history",
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="patient_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="patient_weight",
            new_name="weight",
        ),
    ]
