# Generated by Django 4.1.7 on 2023-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorinformation",
            name="doctor_wallet",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="patientinformation",
            name="patient_wallet",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="SharedPrescriptions",
        ),
    ]
