# Generated by Django 4.1.7 on 2023-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinformation",
            name="history",
            field=models.TextField(),
        ),
    ]
