# Generated by Django 4.1.7 on 2023-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prescriptions",
            "0002_rename_doctor_hospital_name_doctorinformation_hospital_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinformation",
            name="dob",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
    ]
