# Generated by Django 3.2.18 on 2023-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_doctorinformation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='patient_wallet',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
