# Generated by Django 4.1.7 on 2023-04-02 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescriptions", "0003_alter_patientinformation_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinformation",
            name="user",
            field=models.OneToOneField(
                default="Doctor",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientinformation",
            name="user",
            field=models.OneToOneField(
                default="Patient",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
