# Generated by Django 4.1.7 on 2023-04-02 03:22

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescriptions", "0004_doctorinformation_user_patientinformation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorinformation",
            name="user",
            field=models.OneToOneField(
                default=builtins.id,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientinformation",
            name="user",
            field=models.OneToOneField(
                default=builtins.id,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
