# Generated by Django 4.1.7 on 2023-04-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0005_alter_doctorinformation_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorinformation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patientinformation",
            name="user",
        ),
    ]
